### ISSUE TITLE
[Question] Report generation

### ISSUE THREAD

**Issue by noraj** [CervantesSec/cervantes#10]
In the features I have seen `One click reports creation` but I didn't found any report generation section in the app or the doc. I guess it's a TODO feature?

**Comment by mesquidar** [comment]
Hi @noraj , 
The reports are generated in the project details
![2022-06-20_11-19](https://user-images.githubusercontent.com/16049893/174569574-c9869307-f184-4e62-a6d5-8788cd243de8.jpeg)

Im working to improve the report template and I have in backlog to add a feature to customize the report

Best regards

**Comment by noraj** [comment]
Ah ok so it is already it's just me who didn't found it. Thanks.
