### ISSUE TITLE
[Feature suggestion] Import/export config and data

### ISSUE THREAD

**Issue by noraj** [CervantesSec/cervantes#12]
I suggest adding having an import /export feature for the configuration and data of the app (users, vuln templates, project data, etc.) so you can quickly backup your project or redeploy it in case of something happens to the host machine.

**Comment by mesquidar** [comment]
Hi @noraj , I am working on a backup/restore system
I hope it will be available on few weeks

I will keep this ticket opened until is released

Thank you
Best regards

**Comment by noraj** [comment]
Yeah sure, ping me when you need testing

**Comment by noraj** [comment]
Seems to work, I was just asking myself if it is necessary to Unicode escape any non-letter character?

![image](https://user-images.githubusercontent.com/16578570/175819450-cb707bf7-dc3c-4fb3-8f14-1069f667d9d6.png)
