### ISSUE TITLE
Exporting vulnerabilities to JIRA

### ISSUE THREAD

**Issue by c0pp3r** [CervantesSec/cervantes#17]
Not sure if this has been brought up before but has there been any thought to creating the ability to export a project's vulnerabilities either directly to jira or a format that jira can easily import?

**Comment by mesquidar** [comment]
Hi @c0pp3r , I will take note of your suggestion and I will add this feature in next iterations :)

Thank you 
Best regards

**Comment by mesquidar** [comment]
Hi @c0pp3r , on our latest release there's already a basic jira integration (tested with jira server)
If you want to try :)

Best regards
