### ISSUE TITLE
An unhandled exception occurred while processing the request.

### ISSUE THREAD

**Issue by Jewel591** [CervantesSec/cervantes#19]
The following error was encountered when creating a new vulnerbility:
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/18155669/178478324-2d6b5767-2df4-4f11-b62c-2db0553c6740.png">

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/18155669/178478464-7ae03e1d-57bd-4e5c-999f-b98a98c31088.png">
Can anyone give some help? Thank very much!

**Comment by mesquidar** [comment]
Hi @Jewel591 I think you left one field on form. Is posible? :)

I have pending to review and improve the form validation, but I had holidays the last 2 weeks but I am coming back tomorrow

Best regards

**Comment by Jewel591** [comment]
Hi @mesquidar , thanks for your reply.
Here are some situations I have encountered, hope it will be of some help to you.
1.This error occurs when I click Vulnerabilities->create and don't see the creating form yet.
2.I have the same problem in Windows 10, centos 7.6 and Kali Linux 2021 environment, and all they deployed by docker.

**Comment by Jewel591** [comment]
Hi @mesquidar , the error in **vulnerabilities creat** has been fixed, but another error happen in **Generrate Report**:
<img width="1685" alt="image" src="https://user-images.githubusercontent.com/18155669/178882502-ab9b14a6-b51a-4956-8842-379b09e00799.png">
<img width="1688" alt="image" src="https://user-images.githubusercontent.com/18155669/178882392-bd25b178-e5ba-4dd7-b19e-8b5161b46577.png">

**Comment by mesquidar** [comment]
Hi @Jewel591 , I can't reproduce your error in my environment can you tell me the steps you donde to reach the error 
And if is possible can you sent me the app logs :)

Thank you
Best regards

**Comment by mesquidar** [comment]
Hi! I will close this issue there's no update in 10 days
If the error persist please reopen this issue :)

Thank you
Best regards
