### ISSUE TITLE
connect errror and docker container always restarting

### ISSUE THREAD

**Issue by Archerkong** [CervantesSec/cervantes#20]
os:centos7
docker version:Docker version 18.09.0, build 626ff85

when a request the url ,it repsonse the state of 502 Bad Gateway nginx/1.23.0
so when i check the docker env ,i find mesq/cervantes and postgres:latest alway restarting state 
i tried stop the containers and start ,the state always staying restarting 

[root@aaaaaa ~]# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                            PORTS                                      NAMES
cb19e52a85cb        nginx:latest        "/docker-entrypoint.…"   About an hour ago   Up About an hour                  0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   cervantes-nginx
fa67c4d015d8        mesq/cervantes      "dotnet Cervantes.We…"   About an hour ago   Restarting (139) 57 seconds ago                                              cervantes-app
c30618d75a50        postgres:latest     "docker-entrypoint.s…"   About an hour ago   Restarting (2) 4 seconds ago                                                 cervantes-db

wait for help.........

**Comment by mesquidar** [comment]
Hi @Archerkong , can you sent me the logs of both containers? :)
You saw any error when you executed the docker-compose up?

Thank you
Best regards

**Comment by mesquidar** [comment]
Hi! I will close this issue there's no update in 10 days
If the error persist please reopen this issue :)

Thank you
Best regards
