### ISSUE TITLE
Feature Request: Replace Google fonts with local fonts

### ISSUE THREAD

**Issue by corsch** [CervantesSec/cervantes#22]
At the moment cervantes is using Google fonts, which requires a client with internet access.

Would it be possible to replace the Google fonts with local fonts?

**Comment by mesquidar** [comment]
Hi @corsch ,thank you for your comment we will move the font to local in next versions :)

Thank you
Best regards

**Comment by mesquidar** [comment]
Replaced online fonts to local fonts

best regards
