### ISSUE TITLE
Bug: tinymce.min.js not found

### ISSUE THREAD

**Issue by corsch** [CervantesSec/cervantes#23]
When opening "Clients" on cervantes dashboard, "tinymce.min.js" script is not found (HTTP 404 / https://localhost:5001/lib/tinymce/js/tinymce/tinymce.min.js)

**Comment by mesquidar** [comment]
Hi @corsch , no worries with tinymce we migration all the solution to summernote editor. Tinymce will be completely removed in next commits :)

Thank you
Best regards

**Comment by mesquidar** [comment]
Deleites tinymce.js from layouts 

best regards
