### ISSUE TITLE
Bug report [Cervantes]

### ISSUE THREAD

**Issue by arthurmotadev** [CervantesSec/cervantes#25]
```
I'd like to share the report of a pentest made by me. Any doubt I'm available.

[Cervantes Test.pdf](https://github.com/CervantesSec/cervantes/files/9365301/Cervantes.Test.pdf)

Waiting for answers.
```

**Comment by mesquidar** [comment]
Hi @arthurmotadev , thank you for your and your time to report these issue.
About the file upload and XSS we were aware of them they will be fixed in next release

We will check the other issues you comment and we will correct them :)

Thank you
Best regards

**Comment by arthurmotadev** [comment]
Thank you for the fast answer. I've only two questions:

- Exists an expected date to the next release ?

- Talking about the possibility of integration with Jira, is there an expected date ?

**Comment by mesquidar** [comment]
Hi @arthurmotadev , its hard to say. I am improving and mantaining the project on my free time.

Some issues you reported has been fixed some days ago so as soon as I can I will release it (I think it will be a couple of weeks)

For the Jira implementation I need to finish one more module and then I will start with Jira :)

Regards!
