### ISSUE TITLE
[Chore] Adding mention to documentation

### ISSUE THREAD

**Issue by noraj** [CervantesSec/cervantes#3]
There is no mention or link to the documentation on the main repository https://github.com/CervantesSec/cervantes.

It would be nice to add the link https://cervantessec.github.io/docs/ to the project settings.

![image](https://user-images.githubusercontent.com/16578570/174493282-557801ff-5902-4d16-be57-9e10ea9f95ec.png)

Example for another project

![image](https://user-images.githubusercontent.com/16578570/174493293-c9221ce8-b037-40a4-ae98-fe6d6f49fae0.png)

I also made this PRs #2, https://github.com/CervantesSec/docker/pull/1, https://github.com/CervantesSec/docs/pull/1

**Comment by mesquidar** [comment]
Already added

Thanks
Kind regards
