### ISSUE TITLE
Section for executive summary or custom sections

### ISSUE THREAD

**Issue by kboykov** [CervantesSec/cervantes#30]
Hey,
Nice work on this project! Keep it on.

I would like to offer a new feature to be able to add custom sections to the reports. For example a mandatory section usually called "Executive summary" is currently missing and it cannot be added.

By adding custom sections for every each Project this system could be fully utilized for both pentesting, risk assessments and infosec audits.

**Comment by mesquidar** [comment]
Hi @kboykov, thanks for your comment and your idea I will take a look and add it in a future versions :)
At the moment you can create a custom report with your own blocks and import it into Cervantes

Thank you!
Best regards :)

**Comment by mesquidar** [comment]
Executive summary summary section already implemented. I will still working with the custom fields sections

Best regards
