### ISSUE TITLE
Import reports from most common vulnerability scanners 

### ISSUE THREAD

**Issue by tboy-hacker** [CervantesSec/cervantes#31]
Guy day love the project but is this feature available

**Comment by mesquidar** [comment]
Hi @tboy-hacker at the moment we have only available CSV to import vuln but the support for others vuln scanners is on our roadmap. 

There's another ticket with the same topic opened https://github.com/CervantesSec/cervantes/issues/29 you can check the status on that ticket.

I will close this
Best regards :)
