### ISSUE TITLE
error al generar reportes

### ISSUE THREAD

**Issue by alexmartz001** [CervantesSec/cervantes#37]
Hola te felicito por tu trabajo, en esta herramienta.

al momento de generar un reporte, la pantalla se pone en blanco, y no muestra nada, en logs de la aplicacion da este error. talvez sabes que se trata.

When generating a report, the screen goes blank, and does not show anything, in the application logs it gives this error. Maybe you know what it's about.

Error	An error ocurred generating Report. User: admin@cervantes.local	SyncActionResultExecutor.Execute => <no type>.lambda_method1315 => ReportController.GenerateDoc

**Comment by mesquidar** [comment]
Buenas @alexmartz001 , necesitaria lgo más de información sobre el problema, pasos que has seguido, es una plantilla personalizada, da algo más de info en los logs?

Aunque. tambien te comento que en febrero saldra la nueva version y la parte de reporting funcionara de forma distinta por lo que este problema debería desaparecer

**Comment by mesquidar** [comment]
Buenas. @alexmartz001 tienes disponible la nueva version
