### ISSUE TITLE
[Bug] UX/UI design for start/end date when creating a project

### ISSUE THREAD

**Issue by noraj** [CervantesSec/cervantes#4]
I actual can't [create](http://localhost/en/Project/Create) a project because of the date validation.

When you pick a date with the calendar selector

![image](https://user-images.githubusercontent.com/16578570/174494768-4d293289-6a91-47e7-ac4e-3b11990c0807.png)

It only fills the date but it seems there are time fields after that are required.

![image](https://user-images.githubusercontent.com/16578570/174494760-e69b51e5-85c3-47e1-b864-17e48e6bbf55.png)

There is no clock picker for the time, but you can fill it manually:

![image](https://user-images.githubusercontent.com/16578570/174494843-b9bfd7a8-021f-4bcc-b8f5-8727309fc282.png)

It's feels not natural and take several tries before understanding what to do. I suggest just removing the time from the date at all.

**Comment by mesquidar** [comment]
Hi @noraj ,

I checked your suggestion and I deleted the time option from the date
![project dates](https://user-images.githubusercontent.com/16049893/174646662-d3de1e95-3066-4b98-8a3e-1b7a76bad806.jpeg)

If you have any doubts do not hesitate to contact me :)

Best regards
