### ISSUE TITLE
Improper handling of CVSS score in vulnerabilities

### ISSUE THREAD

**Issue by jstangle** [CervantesSec/cervantes#48]
If you make any edits to the vulnerability, the CVSS score automatically reverts to the default value of 10 ~ Critical.

# Steps to reproduce:
- Create a new vulnerability
- Define some name and CVSS score, for example medium 5.0 (CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:L/I:N/A:N)
- Click "EDIT" to save the vulnerability
- Open the vulnerability and click to edit
- You can make some changes and then click to "EDIT"
- Open the vulnerability and see the CVSS, the originally defined CVSS was reverted to default value of 10 ~ Critical.

![Screenshot from 2024-08-08 14-46-24](https://github.com/user-attachments/assets/9957a5fb-b87a-4ea5-9ec3-70d874873c98)

![Screenshot from 2024-08-08 14-45-21](https://github.com/user-attachments/assets/98e6d780-d441-4da2-bd77-12c113bda927)

**Comment by mesquidar** [comment]
Hi @jstangle thanks for reporting this issue I will take it a look and I will let you know :)

Thank you
Best regards

**Comment by mesquidar** [comment]
Hi  @jstangle I found the issue and I think is fixed I created a dev image if you want to test it before to commit the changes :)

```sh
git clone https://github.com/CervantesSec/docker.git
```

* After that you need to start your docker containers:

```sh
docker-compose -p cervantes -f docker-compose-dev.yml up -d
```

Thank you :)
Best regards

**Comment by jstangle** [comment]
Hi @mesquidar, thanks for the quick response! I tested it and it's working fine. I noticed one more issue related to CVSS rating. CVSS rating in the vulnerability view always stays "Critical" even if calculation comes out differently.
![image](https://github.com/user-attachments/assets/1706fcfb-909c-4bdf-9486-5318af45c6a0)

**Comment by mesquidar** [comment]
Hi @jstangle thanks for confirming that is working fine. About the "Critical" displaying issue it should be fixed too I will push the changes and create a new image

Thank you 
Best regards
