### ISSUE TITLE
[UI Design] Avatar image crop instead of stretch

### ISSUE THREAD

**Issue by noraj** [CervantesSec/cervantes#5]
## Actual behavior - stretch

For example, for project avatar, a 16:9 rectangular is casted to a square of 1:1 then rounded but it results in stretched image and poor result.

![image](https://user-images.githubusercontent.com/16578570/174495801-4091e9db-f7f2-4283-b9e2-ccfdf4b03927.png)

Bonus: here the image height is fixed to 200px but the width is dynamic constrained only by `max-width: 100%;` so it ends with an image of 220.667px * 200px

## Expected behavior - crop/cover

Changing aspect ratio always looks terrible so instead the solution is just to crop.

![image](https://user-images.githubusercontent.com/16578570/174495860-f8f36a90-4d17-4c37-a3bb-5df040750c72.png)

The solution with bootstrap is to not use the image tag because bootstrap is not very flexible with them. Instead use a div with whatever custom class and this rules applied to this class:

```css
background-image: url("url");
width:200px;
height:200px;
background-size:cover;
background-position:center;
border-radius:50%;
```

Bonus: here the image is pure 200*200px

**Comment by noraj** [comment]
> Bonus: here the image height is fixed to 200px but the width is dynamic constrained only by `max-width: 100%;` so it ends with an image of 220.667px * 200px

We can more clearly see the issue with the fake circle on workspace image, this time the "circle" is 355,55x200px and so the aspect ratio appears less distorted.

![image](https://user-images.githubusercontent.com/16578570/174496912-ae701dc0-2394-415b-94b0-115782efd395.png)

By applying the previous suggested solution + `d-flex justify-content-center` on the parent container it looks like this

![image](https://user-images.githubusercontent.com/16578570/174497074-524d0c90-ec82-4206-8638-2f8bad72dab8.png)

**Comment by noraj** [comment]
User avatars in Project members table are heavily distorted too

![image](https://user-images.githubusercontent.com/16578570/174497148-7bd4b5c0-0ac7-432e-8e66-75c27a6463d6.png)

Here what it results with still the same previous solution and a size of 2.5rem (actual width)

![image](https://user-images.githubusercontent.com/16578570/174497252-278c4df6-e194-474e-ac6d-d127ac7b2a6b.png)

And here with 1.25rem (actual height)

![image](https://user-images.githubusercontent.com/16578570/174497315-81e2bd55-5960-4f14-a006-d5ed62cb7bc2.png)

**Comment by mesquidar** [comment]
new version available
