### ISSUE TITLE
Invalid data mapping in Scriban variable {{VulnJira}}

### ISSUE THREAD

**Issue by jstangle** [CervantesSec/cervantes#50]
{{VulnJira}} is displaying the CVSS vector instead of the Jira key for the vulnerability.

# Steps to reproduce:
- Create a Report Component containing the following string:
`{{tablerow vuln in Vulns}}{{if vuln.VulnJiraCreated; vuln.VulnJira; end}}{{end}}`
- Attach the Component to a Report template
- Create a Report using the aforementioned Report template
- Check the output in the Report

![image](https://github.com/user-attachments/assets/ccc4d7a3-1d3d-4de4-90ef-4037e2754e5c)
![image](https://github.com/user-attachments/assets/ac0f2efb-05fb-4822-a34a-5635db3f2c2c)

**Comment by mesquidar** [comment]
Hi @jstangle thanks for reporting this issue I will take it a look and I will let you know :)

Thank you
Best regards

**Comment by mesquidar** [comment]
Hi  @jstangle I found the issue and I think is fixed and I also added new variables ready to use:

- {{VulnJira}}
- {{VulnJiraStatus}}
- {{VulnJiraDueDate}}
- {{VulnJiraCreatedDate}}
- {{VulnJiraResolutionDate}}
- {{VulnJiraResolution}}
- {{VulnJiraPriority}}
- {{VulnJiraAssigned}}
- {{VulnJiraType}}
- {{VulnJiraComponent}}
- {{VulnJiraComponent}}

I created a dev image if you want to test it before to commit the changes :)

```sh
git clone https://github.com/CervantesSec/docker.git
```

* After that you need to start your docker containers:

```sh
docker-compose -p cervantes -f docker-compose-dev.yml up -d
```


Thank you :)
Best regards

**Comment by jstangle** [comment]
Hi @mesquidar, thank you! I can confirm it is working.
