### ISSUE TITLE
Add mapping for “Created Date” to Scriban variable {{DocumentCreated}}

### ISSUE THREAD

**Issue by jstangle** [CervantesSec/cervantes#53]
Can you please add a mapping for the report’s “Created Date” to the Sriban variable {{DocumentCreated}}?

![image](https://github.com/user-attachments/assets/6e9b122e-a386-4a42-b98f-5c4bc753db16)

**Comment by mesquidar** [comment]
Hi @jstangle yes sure no problem I will create a new image with the variable included

Regards

**Comment by mesquidar** [comment]
Already added in the new stable and dev image 

Thank you
Best regards

**Comment by jstangle** [comment]
Thank you very much! :-)

**Comment by mesquidar** [comment]
I didn't comment it but the variable is {{DocumentCreatedDate}} :)

**Comment by jstangle** [comment]
@mesquidar thank you! I can confirm that variable is working. I also noticed that the array of Documents seems to be updated after a new report is generated, so the latest version of the document is not immediately reflected in the array.

I have created 3 reports, the latest has the version number 1.2
![image](https://github.com/user-attachments/assets/e4adc9c0-fe97-4691-b02f-3d538261dff3)

Sriban in the template:
`{{ for doc in Documents }}Version: {{ doc.DocumentVersion }} Name: {{ doc.DocumentName }} Date: {{ doc.DocumentCreatedDate }} Changes: {{ doc.DocumentDescription }}{{ end }}`

Output in the report 1.2:
```
Version: 1.1 Name: Tralala Date: 8/16/2024 Changes: Added links
Version: 1.0 Name: Tralala Date: 8/16/2024 Changes: Initial release
```
The array is missing the latest document.

**Comment by mesquidar** [comment]
Hi @jstangle this should be fixed in the new image :)

Regards
