### ISSUE TITLE
Incorrect CVSS score calculation

### ISSUE THREAD

**Issue by jpostolk** [CervantesSec/cervantes#54]
When setting the scope parameter to unchanged, the resulting CVSS score is higher than expected. Changed scope and all other parameters seem to be OK.

# Example

![Screenshot from 2024-08-20 12-38-40](https://github.com/user-attachments/assets/341d9002-9a65-4d92-8596-d7717a364379)
![Screenshot from 2024-08-20 12-39-34](https://github.com/user-attachments/assets/4ca40535-6bc7-4a16-b79a-2d16f4203a18)

**Comment by mesquidar** [comment]
Hi @jpostolk thanks for reporting this issue I will take it a look and I will let you know :)

Thank you
Best regards

**Comment by mesquidar** [comment]
Hi  @jpostolk  I found the issue and It should be fixed I created a dev image if you want to test it  :)

```sh
git clone https://github.com/CervantesSec/docker.git
```

* After that you need to start your docker containers:

```sh
docker-compose -p cervantes -f docker-compose-dev.yml up -d
```

Thank you :)
Best regards

**Comment by jpostolk** [comment]
Hi @mesquidar, I can confirm the issue is fixed. 

Thank you very much :)
Best regards

**Comment by mesquidar** [comment]
@all-contributors please add @jpostolk  for bug
