### ISSUE TITLE
Unexpected table row when using tablerow element in Scriban

### ISSUE THREAD

**Issue by jstangle** [CervantesSec/cervantes#55]
When using tablerow element in Scriban it produces an unexpected empty table row. I tested the array doesn't have any empty items.

# Example
```{{tablerow user in Users}}{{user.UserFullName}}{{user.UserEmail}}{{user.UserPosition}}{{end}}```

![Screenshot from 2024-08-20 16-04-14](https://github.com/user-attachments/assets/6cd1c759-529e-460e-b68f-3b449f620c1d)

![Screenshot from 2024-08-20 16-06-38](https://github.com/user-attachments/assets/fc368d5e-2fd8-407a-b0a5-6d5293322072)

**Comment by mesquidar** [comment]
Hi @jstangle  thanks for reporting this issue I was aware of this issue is related how scriban works to generate the table rows but I didn't have enough time to try to tweak it. 

I will keep the issue open until I release the fix

Thank you :)
Best regards

**Comment by mesquidar** [comment]
Hi @jstangle @jpostolk I created a new dev image with a tweak on tablerow. This tweak substitutes tablerow with a for loop that creates the rows 

if you want to test it  :)

```sh
git clone https://github.com/CervantesSec/docker.git
```

* After that you need to start your docker containers:

```sh
docker-compose -p cervantes -f docker-compose-dev.yml up -d
```

Thank you :)
Best regards

**Comment by jstangle** [comment]
Hi @mesquidar, Thank you for fixing the issue.
