### ISSUE TITLE
Web UI Enhancement Ideas

### ISSUE THREAD

**Issue by EmiliaChovancova** [CervantesSec/cervantes#56]
I would like to propose a change to the “Edit” button. When you’re editing a component, vulnerability etc. you want to save the changes - so it might make more sense to change the button to “Save”.

![Screenshot 2024-08-14 at 12 07 51](https://github.com/user-attachments/assets/c7191935-99d5-48c9-b088-dc6a9f88257f)

---
The second one would be that in Firefox, if you go to Project and you switch between the menu tabs - Details, Executive summary etc. the line under the current tab is not corresponding to the particular tab you clicked on.  

<img width="429" alt="tabFirefox" src="https://github.com/user-attachments/assets/c789a644-3a8c-4d50-b4fa-7ea7260be632">
 
But it’s working with chrome: 
![tabChrome](https://github.com/user-attachments/assets/7c884380-01a0-4aa1-8d1a-d486e164642a)

---
The last one is present in a logo of a profile - if you change the logo of the profile, the logo is not present by the profile in the top part of the page. 

![Screenshot 2024-08-21 at 14 22 39](https://github.com/user-attachments/assets/a0bccace-525c-4908-b6b6-b2b57dbf688c)

wdyt? :)

**Comment by EmiliaChovancova** [comment]
Hi @mesquidar, thank you :)

**Comment by mesquidar** [comment]
Hi @EmiliaChovancova the profile logo and tab display problem should be fixed there's a new image created :)

Thank you 
Best regards

**Comment by EmiliaChovancova** [comment]
Hi @mesquidar, thank you!  :)

**Comment by mesquidar** [comment]
Hi @EmiliaChovancova changed the button naming and the tab fix is added I will close this issue :)

Thank you
Bets regards
