### ISSUE TITLE
No Default password

### ISSUE THREAD

**Issue by tonijack99** [CervantesSec/cervantes#57]
I have installed CervantesSec on both Kali and CentOS9 servers however when using the build command:
docker-compose -p cervantes -f docker-compose.yml up -d
No output of default password
" 
![image](https://github.com/user-attachments/assets/0777e451-4f8e-44eb-bbf1-3bb437f51596)
 What should I do now?

**Comment by mesquidar** [comment]
Hi @tonijack99 the default password is generated inside the cervantes-app container logs not in the docker-compose output

You can check the password  with
`docker logs cervantes-app` or `docker logs [container id]`

Best regards

**Comment by tonijack99** [comment]
Thanks, I will check the log again.

**Comment by tonijack99** [comment]
> Hi @tonijack99 the default password is generated inside the cervantes-app container logs not in the docker-compose output
> 
> You can check the password with `docker logs cervantes-app` or `docker logs [container id]`
> 
> Best regards

Thanks I got the pass info. It's a hash but I logged in and changed the pass
