### ISSUE TITLE
Add "Author" column in Vulnerabilites Table

### ISSUE THREAD

**Issue by jstangle** [CervantesSec/cervantes#58]
Hello, to improve collaboration within the team, it would be very beneficial to identify who added each vulnerability to the project. Could you add an 'Author' column to the Vulnerabilities table?

![image](https://github.com/user-attachments/assets/ba376ee1-baa5-49d3-b81c-38f4a29b290a)

**Comment by mesquidar** [comment]
Hi @jstangle sure no problem it's already added :)

Thank you
Best regards

**Comment by jstangle** [comment]
Thank you! :-)
