### ISSUE TITLE
[Feature suggestion] Access to the template DB globally

### ISSUE THREAD

**Issue by noraj** [CervantesSec/cervantes#8]
I tested to create multiple projects and the vulnerability template database seems to be shared among all projects (which is a good thing). However the template page can be access only from a workspace. So if no workspace is selected you can access it. But since the template DB is not attached to a particular project it make sense to be able to reach it globally.

![image](https://user-images.githubusercontent.com/16578570/174497602-0b885562-a16a-4f00-b2b8-cf1e53697b8a.png)

I suggest adding a button / link to the template DB either in the Vulnerabilities drop-down in the General section or in the top navbar.

Use case, when reviewing a report of a mate you find a typo in it's the vulnerability description that is inherited from the template, you want to fix the report of course but also to fix the template since you don't want to have to fix it for every report. At this moment you want to access the template DB directly to make your change and not to select a workspace to be able to select the global template DB.

**Comment by mesquidar** [comment]
Hi @noraj ,

I reviewed your comment and I added the  Templates option in the General Section :)

![templates global](https://user-images.githubusercontent.com/16049893/174644432-e92a62e4-3710-4228-9211-fadbd9719c47.jpeg)

Best regards

**Comment by noraj** [comment]
Nice, thanks
