### ISSUE TITLE
[chore] Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by noraj** [CervantesSec/cervantes#9]
> Before you jump to make any changes make sure you have read the [contributing guidelines](https://github.com/CervantesSec/cervantes/blob/main/CONTRIBUTING.md). This would save us all time. Thanks!

The readme contains a _contributing guidelines_ link but there is none in the repo resulting in a 404.

**Comment by mesquidar** [comment]
Added Contributing to repo

best regards
